### PR TITLE
Introduce `--pre-resolved-dists` resolver.

### LINKED ISSUE #1907: Pex CLI doesn't offer as much control over pex building process as the PEXBuilder
As a major PEX user twitter leverages the PEXBuilder class to build pexes instead of shelling out to the PEX cli for a few reasons.

1. The `--sources-directory` option to add sources to a pex doesn't offer fine enough control over the final import paths of source files. In order to make `--sources-directory` work we would have to prepare all the sources in merged directories. E.g Often multiple directories need to be merged into the same Chroot directory.
2. We make use of PEXBuilder.add_dist_location to add pre-installed wheels (unzipped wheels) to pexes. We have found that the overhead of using direct file URLs via `--requirement` on the CLI and even the main `PEXBuilder.add_distribution` methods to add significant overhead by invoking pip.pex for each distribution. We can improve build times significantly by relying on the existence of a mechanism for fetching 3rdparties that is outside of pex itself.
3. ... will update if I think of more ...

These may not be things that the Pex CLI wants to support but figured I would list them out based on the fact that PEXBuilder isn't under a stable API contract with users.

### PR DESCRIPTION
**Pull request by jsirois**
When building a PEX or creating a venv via `pex3 venv create` you can
now tell Pex to use a set of pre-resolved distributions. This is similar
to using `--no-pypi --find-links ...` except that:
1. Its roughly 3x faster since Pip is not asked to do any resolution.
2. It requires all the distributions specified form an already complete
   resolve.

One way to obtain distributions that meet criteria 2 is to use
`pip download -d ...` or `pip wheel -w ...` to pre-resolve the
distributions you need.

Closes #1907

### CODE REVIEW

**Comment by jsirois** [comment]
@hrfuller I think this solves the last discrepancy in #1907. Although you can't add dists via the Pex API, you can do so using this new `--pre-resolved-dists`. I know you're now separated from your original use case; so can't test the speed difference, but it should be ~same. I included some perf test results above at any rate. One advantage over adding dists via the API is that this supports sub-setting; i.e. point at one big consistent resolve pool of dists with `--pre-resolved-dists ...` and you can resolve the whole thing or any subset by just changing the root requirement list you hand Pex.

**Comment by jsirois** [comment]
Pants folks, I added you since this may be one way to get `uv` in the loop, since its a way to have Pex step out of the resolve loop. Although neither [`uv pip download`](https://github.com/astral-sh/uv/issues/3163) nor [`uv pip wheel`](https://github.com/astral-sh/uv/issues/1681) exist today, they don't sound completely opposed. They just need someone to do the work.

**Comment by jsirois** [comment]
@zmanji this might be a way for you to get offline Pex support, re: https://github.com/pex-tool/pex/issues/2201#issuecomment-1694144209

**Comment by jsirois** [comment]
N.B.: The bulk of the delta lines is a test lockfile at ~1800 lines.

**Comment by zmanji** [comment]
> @zmanji this might be a way for you to get offline Pex support, re: [#2201 (comment)](https://github.com/pex-tool/pex/issues/2201#issuecomment-1694144209)

Yes with this flag pex can work in a docker container without internet access or with nix or similar.

I am assuming the workflow if you have a lockfile will be:
1. Export the lock to `requirements.txt`, creating a subset if needed
2. Use pip to download all of the artifacts.
3. Use `--pre-resolved-dists` with the `requirements.txt` to build the resulting pex.

**Comment by jsirois** [comment]
@zmanji yes, exactly. The tests do this here:
https://github.com/pex-tool/pex/pull/2512/files#diff-3aad399daa6b77a0c3e83cdca2225461ef07f4aebe306abdb80ed4b8bfd2fb19R39-R45

You do have to ensure that either the download or the original lock, though, is 100% wheels of course.

**Review by zmanji — APPROVED** [review]
Overall the code/tests and idea lgtm!

**Pull request merged**
